image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  APP_IMAGE: demo-cicd-image 

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:3.8.5-openjdk-17
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:3.8.5-openjdk-17
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
  - docker build -t $APP_IMAGE .
  - docker run -d -p 8090:8080 $APP_IMAGE
