
stages:
  - build
  - deploy

build:
  stage: build
  image: 
    name: maven:3.8.5-openjdk-17
  script: mvn clean install
  artifacts:
    paths:
      - target/spring-gitlab-ci*

production:
  stage: deploy
  image: 
    name: docker:latest  
  script:
  - docker build -t demo-cicd-image .
  only:
  - main

after_script:
  - echo "End CI/CD Process"
