stages:
  - build
  - deploy

build:
  stage: build
  image: 
    name: maven:3.8.5-openjdk-17
  script: mvn clean install
  artifacts:
    paths:
      - target/spring-gitlab-ci*

production:
  stage: deploy
  image: 
    name: docker:latest  
  services:
    - docker:dind   
  variables:
    DOCKER_HOST: tcp://docker:2378
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
  - docker build -t demo-cicd-image .
  - docker run -d -p 8080:8090 demo-cicd-image
  only:
  - main

after_script:
  - echo "End CI/CD Process"
