stages:
  - build
  - deploy

# This fixes "error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on <Serverip> no such host"
variables:
  # DOCKER_HOST variable tells docker how to connect to the daemon (a background service running inside the Docker VM)
  DOCKER_HOST: tcp://docker:2375/
  # Environemt Variable for docker:dind service explaining to use overlay2 as supporting driver for docker
  # https://docs.docker.com/storage/storagedriver/overlayfs-driver/
  DOCKER_DRIVER: overlay2
  # We need to disable TLS (https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/#disable-tls)
  # to fix the error "docker: Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?"
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: 
    name: maven:3.8.5-openjdk-17
  script: mvn clean install
  artifacts:
    paths:
      - target/spring-gitlab-ci*

production:
  stage: deploy
  image: 
    name: docker:latest  
  services:
    - docker:dind   
  script:
  - docker build -t demo-cicd-image .
  - docker run -d -p 8080:8090 demo-cicd-image
  only:
  - main

after_script:
  - echo "End CI/CD Process"
