image: openjdk:17-alpine

stages:
  - build
  - deploy

build:
  stage: build
  script: $MAVEN_HOME/bin/mvn clean install
  artifacts:
    paths:
      - target/spring-gitlab-ci*

production:
  stage: deploy
  script:
  - docker build -t demo-cicd-image .
  only:
  - main

after_script:
  - echo "End CI/CD Process"
